/*
 * Copyright 2022-2024, Zhichun Wu
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.github.jdbcx.driver;

import java.sql.SQLException;
import java.sql.Statement;

interface ExecuteCallback {
    boolean execute(String query) throws SQLException;

    int executeUpdate(String query) throws SQLException;
}

class BaseExecuteCallback implements ExecuteCallback {
    protected final Statement stmt;

    BaseExecuteCallback(Statement stmt) {
        this.stmt = stmt;
    }

    @Override
    public boolean execute(String query) throws SQLException {
        return stmt.execute(query);
    }

    @Override
    public int executeUpdate(String query) throws SQLException {
        return stmt.executeUpdate(query);
    }
}

final class ExecuteWithFlag extends BaseExecuteCallback {
    private final int autoGeneratedKeys;

    ExecuteWithFlag(Statement stmt, int autoGeneratedKeys) {
        super(stmt);
        this.autoGeneratedKeys = autoGeneratedKeys;
    }

    @Override
    public boolean execute(String query) throws SQLException {
        return stmt.execute(query, autoGeneratedKeys);
    }

    @Override
    public int executeUpdate(String query) throws SQLException {
        return stmt.executeUpdate(query, autoGeneratedKeys);
    }
}

final class ExecuteWithIndex extends BaseExecuteCallback {
    private final int[] columnIndexes;

    ExecuteWithIndex(Statement stmt, int[] columnIndexes) {
        super(stmt);
        this.columnIndexes = columnIndexes;
    }

    @Override
    public boolean execute(String query) throws SQLException {
        return stmt.execute(query, columnIndexes);
    }

    @Override
    public int executeUpdate(String query) throws SQLException {
        return stmt.executeUpdate(query, columnIndexes);
    }
}

final class ExecuteWithNames extends BaseExecuteCallback {
    private final String[] columnNames;

    ExecuteWithNames(Statement stmt, String[] columnNames) {
        super(stmt);
        this.columnNames = columnNames;
    }

    @Override
    public boolean execute(String query) throws SQLException {
        return stmt.execute(query, columnNames);
    }

    @Override
    public int executeUpdate(String query) throws SQLException {
        return stmt.executeUpdate(query, columnNames);
    }
}