-- https://duckdb.org/docs/sql/data_types/overview
create table basic_types (
	c_blob        BLOB,
	c_boolean     BOOLEAN,
	c_bit         BIT,
	c_tinyint     TINYINT,
	c_utinyint    UTINYINT,
	c_smallint    SMALLINT,
	c_usmallint   USMALLINT,
	c_integer     INTEGER,
	c_uinteger    UINTEGER,
	c_bigint      BIGINT,
	c_ubigint     UBIGINT,
	c_hugeint     HUGEINT,
	c_uhugeint    UHUGEINT,
	c_real        REAL,
	c_double      DOUBLE,
	c_decimal     DECIMAL,
	c_decimal18   DECIMAL(18, 0),
	c_decimal183  DECIMAL(18, 3),
	c_date        DATE,
	c_interval    INTERVAL,
	c_time        TIME,
	c_timestamp   TIMESTAMP,
	c_timestamps  TIMESTAMP_S,
	c_timestampms TIMESTAMP_MS,
	c_timestampns TIMESTAMP_NS,
	c_timestamptz TIMESTAMPTZ,
	c_uuid        UUID,
	c_varchar     VARCHAR,
	c_varchar1    VARCHAR(1),
	c_varchar2    VARCHAR(2),
	c_int_array   INT[3],
	c_int_list    INT[],
	c_map         MAP(INT, VARCHAR), 
	c_struct      STRUCT(i INT, j VARCHAR), 
	c_union       UNION(num INT, text VARCHAR)
)
