name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**/docs/**"
      - "**/LICENSE"
      - "**/NOTICE"

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "**.md"
      - "**/docs/**"
      - "**/LICENSE"
      - "**/NOTICE"

  workflow_dispatch:
    inputs:
      pr:
        description: "Pull request#"
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Compile using JDK 8
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check out PR
        run: |
          git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 \
            origin pull/${{ github.event.inputs.pr }}/merge:merged-pr && git checkout merged-pr
        if: github.event.inputs.pr != ''
      - name: Install JDK 8 and Maven
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 8
          cache: "maven"
      - name: Build and install libraries
        run: mvn --batch-mode --show-version --strict-checksums --threads 2 -Dmaven.wagon.rto=30000 -Dj8 install

  test-jdk17:
    needs: compile
    strategy:
      matrix:
        # https://whichjdk.com/
        # https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#selecting-a-java-distribution
        dist: ["corretto", "liberica", "microsoft", "temurin", "zulu"]
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    name: ${{ matrix.dist }} JDK 17 on ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check out PR
        run: |
          git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 \
            origin pull/${{ github.event.inputs.pr }}/merge:merged-pr && git checkout merged-pr
        if: github.event.inputs.pr != ''
      - name: Install JDK 17 and Maven
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.dist }}
          java-version: 17
          cache: "maven"
      - name: Setup Toolchain
        shell: bash
        run: |
          mkdir -p $HOME/.m2 \
          && cat << EOF > $HOME/.m2/toolchains.xml
          <?xml version="1.0" encoding="UTF8"?>
          <toolchains>
            <toolchain>
              <type>jdk</type>
              <provides>
                <version>17</version>
              </provides>
              <configuration>
                <jdkHome>${{ env.JAVA_HOME }}</jdkHome>
              </configuration>
            </toolchain>
          </toolchains>
          EOF
      - name: Test libraries
        run: mvn --batch-mode --show-version --strict-checksums install
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: result ${{ github.job }}
          path: |
            **/target/failsafe-reports
            **/target/surefire-reports
