name: Docker

on:
  workflow_dispatch:
    inputs:
      major:
        description: "Major version"
        required: true
        default: "0"
      minor:
        description: "Minor version"
        required: false
        default: "5"
      patch:
        description: "Patch"
        required: false
        default: "0"
      owner:
        description: "DockerHub owner"
        required: false
        default: "jdbcx"
      pr:
        description: "Pull request#"
        required: false

jobs:
  publish:
    name: "Build and Publish Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check out PR
        run: |
          git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 \
            origin pull/${{ github.event.inputs.pr }}/merge:merged-pr && git checkout merged-pr
        if: github.event.inputs.pr != ''
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWD }}
      - name: Build and Push Base Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.base
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            JDBCX_VERSION=${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}
          tags: |
            ${{ github.event.inputs.owner }}/jdbcx-base:latest
            ${{ github.event.inputs.owner }}/jdbcx-base:${{ github.event.inputs.major }}
            ${{ github.event.inputs.owner }}/jdbcx-base:${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}
            ${{ github.event.inputs.owner }}/jdbcx-base:${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}
      - name: Build and Push Minimal Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.event.inputs.owner }}/jdbcx:latest
            ${{ github.event.inputs.owner }}/jdbcx:${{ github.event.inputs.major }}
            ${{ github.event.inputs.owner }}/jdbcx:${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}
            ${{ github.event.inputs.owner }}/jdbcx:${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}
      - name: Build and Push Full Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.full
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.event.inputs.owner }}/jdbcx-full:latest
            ${{ github.event.inputs.owner }}/jdbcx-full:${{ github.event.inputs.major }}
            ${{ github.event.inputs.owner }}/jdbcx-full:${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}
            ${{ github.event.inputs.owner }}/jdbcx-full:${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}
